language: node_js
node_js:
  - 17
deploy:
  provider: pages
  strategy: git
  os: linux
  dist: focal
  cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: main
cache: npm
script:
  - npm cache clean --force
  - npm install